project_name: jiracli
release:
  gitlab:
    owner: rhysjtevans
    name: jiracli
  name_template: '{{.Tag}}'
scoop:
  name: jiracli
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
  goamd64: v1
builds:
  - id: jiracli
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    goarm:
      - "6"
    gomips:
      - hardfloat
    goamd64:
      - v1
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
    dir: .
    main: .
    binary: jiracli
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
# archives:
#   - id: default
#     name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
#     format: tar.gz
#     files:
#       - src: license*
#       - src: LICENSE*
#       - src: readme*
#       - src: README*
#       - src: changelog*
#       - src: CHANGELOG*
snapshot:
  name_template: '{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256
dist: dist
env_files:
  github_token: ~/.config/goreleaser/github_token
  # gitlab_token: ~/.config/goreleaser/gitlab_token
  # gitea_token: ~/.config/goreleaser/gitea_token
source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz
gomod:
  gobinary: go
github_urls:
  download: https://github.com
